### ISSUE TITLE
minor changes in grammar prevent highlighting

### ISSUE THREAD

**Issue by RalphAS** [ronisbr/julia-ts-mode#10]
It appears that the treesitter julia grammar has recently changed in (at least) the following ways which break this package:
* `global_declaration` and `local_declaration` are now `global_statement` and `local_statement`
* in a `type_clause`, `"<:"` is now parsed as "operator" instead of the literal string

The changes to font-lock settings are easy, but I have no idea how to enforce consistency with versions of the grammar.

**Comment by ggebbie** [comment]
RalphAS : thank you for posting. Yesterday I installed emacs 29.0.92, tree-sitter, and julia-ts-mode and found that syntax highlighting was not working for me (ubuntu 22.04). Perhaps it is the same issue? Here is the error message:
```
Error during redisplay: (jit-lock-function 1) signaled (treesit-query-error "Node type error at" 350 "(assignment (identifier) @font-lock-variable-name-face (_)) (assignment (field_expression (identifier) \".\" (identifier) @font-lock-variable-name-face) (operator)) (assignment (bare_tuple (identifier) @font-lock-variable-name-face)) (assignment (bare_tuple (field_expression (identifier) \".\" (identifier) @font-lock-variable-name-face)) (operator)) (local_declaration (identifier) @font-lock-variable-name-face) (let_binding (identifier) @font-lock-variable-name-face) (global_declaration (identifier) @font-lock-variable-name-face)" "Debug the query with `treesit-query-validate'") [2 times]
```

**Comment by RalphAS** [comment]
Yes, that is is the critical symptom. You can try the changes in PR #11 on your system.

**Comment by ggebbie** [comment]
changes in PR #11 work for me to have syntax highlighting with `treesit-font-lock-level` 1, 2, or 3.  Thanks so much RalphAS.  Also thanks to ronisbr and team for putting this together.

Note, `treesit-font-lock-level` 4 gives an error
```elisp
Query pattern is malformed: "Node type error at", 371, "(adjoint_expression \"'\" @font-lock-type-face) (let_binding \"=\" @font-lock-type-face) (for_binding [\"=\" \"∈\"] @font-lock-type-face) (function_expression \"->\" @font-lock-type-face) (operator) @font-lock-type-face (slurp_parameter \"...\" @font-lock-type-face) (splat_expression \"...\" @font-lock-type-face) (ternary_expression [\"?\" \":\"] @font-lock-type-face) (type_clause [\"<:\" \">:\"] @font-lock-type-face) ([\".\" \"::\"] @font-lock-type-face)", "Debug the query with `treesit-query-validate'"
```

**Comment by ronisbr** [comment]
Hi @ggebbie !

Can you please provide a MWE with the code that gives the error?

@RalphAS thank you very much for fixing the issue!

**Comment by ronisbr** [comment]
Never mind, the `type_clause` also changed. I fixed this error but I found a bug in the grammar reported here:

https://github.com/tree-sitter/tree-sitter-julia/issues/108

**Comment by ggebbie** [comment]
thanks @ronisbr  -- you beat me to it. nice work!
