### ISSUE TITLE
Readme should state on how to install the grammar

### ISSUE THREAD

**Issue by mauro3** [ronisbr/julia-ts-mode#13]
It would be helpful if the Readme stated on how to install the grammar, or at least give (opinionated) links to instructions.

x-ref: https://github.com/tree-sitter/tree-sitter-julia/issues/115

**Comment by ronisbr** [comment]
Thanks for the suggestion! I will do this!

**Comment by ronisbr** [comment]
Done! It turns out that using the package `treesit-auto` is by far the easiest method. It can automatically download and compile the grammars for the supported languages, including Julia.

**Comment by mauro3** [comment]
Just installed the treesit-auto with the option to ask to install missing grammar (`(setq treesit-auto-install 'prompt)`) and seems to work well.  Thanks!
