### ISSUE TITLE
Make julia-ts-mode a derived mode of julia-mode

### ISSUE THREAD

**Issue by non-Jedi** [ronisbr/julia-ts-mode#2]
Hi @ronisbr. Opening an issue here to avoid cluttering the issue on the main julia-mode repo.

>By the way, until julia-ts-mode is merged here, I needed to replicate some functionality. Hence, I copied all the code related with LaTeX symbol substitution. Now, I think it is working to the point I can start using it daily.

This is why I recommended making `julia-ts-mode` a derived mode of `julia-mode`. As I understand it, `define-derived-mode` basically does object-oriented inheritance. If you define `julia-ts-mode` as a derived mode of `julia-mode`, not only do you get access to all the niceties from `julia-mode` for free but also things like `eglot-jl` and `julia-snail-mode` which rely on checking whether the major mode is `julia-mode` will work with `julia-ts-mode` without modification.

This should be advantageous even for the relatively brief time where you're developing `julia-ts-mode` independently before we merge with `julia-mode`. Even after we merge, we may want to keep `julia-ts-mode` separate from `julia-mode` so that people can continue to use the existing fontification and indentation implementations for cases where they're having one issue or another with treesitter.

You would just need to override `syntax-propertize-function` `indent-line-function` to `nil` so that they don't compete with treesit. I would make a quick PR myself (should just be 3 lines of changes and a lot of stuff that can be deleted), but I don't have emacs 29 available right now to test it with.

**Comment by ronisbr** [comment]
Perfect! Thank you very much, I will do that!

**Comment by ronisbr** [comment]
Hi @non-Jedi !

It was easier than I thought! However, I did not test it deeply.

The LSP configuration did not work out-of-the-box. I needed to register manually `julia-ts-mode`.
