### ISSUE TITLE
Don't indent module block contents

### ISSUE THREAD

**Issue by non-Jedi** [ronisbr/julia-ts-mode#3]
Reading through @chriselrod's evaluation of which existing `julia-mode` issues are resolved by `julia-ts-mode` (thanks @chriselrod!), I thought I'd file issues for the few problems that you might have some control over.

It appears from the testing of https://github.com/JuliaEditorSupport/julia-emacs/issues/12, that `julia-ts-mode` tries to indent the contents of a module which is not in keeping with the style guide from the Julia manual.

EDIT: I thought there were a couple of other things I saw, but re-reading the comment this is the only one that jumps out to me. :shrug:

**Comment by ronisbr** [comment]
Nice catch! Thanks @non-Jedi! It should be correct now :)
